# Generated by Django 4.0.4 on 2022-04-24 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('data_inicio', models.DateField(auto_now_add=True)),
                ('data_final', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('risco', models.IntegerField()),
                ('participantes', models.TextField()),
            ],
        ),
    ]
