# Generated by Django 4.0.4 on 2022-04-24 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='data_final',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='data_inicio',
            field=models.CharField(max_length=10),
        ),
    ]
