# Generated by Django 4.0.4 on 2022-04-24 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0002_alter_projeto_data_final_alter_projeto_data_inicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeto',
            old_name='data_final',
            new_name='dataInicio',
        ),
        migrations.RenameField(
            model_name='projeto',
            old_name='data_inicio',
            new_name='dataTermino',
        ),
    ]
